#!/usr/bin/env python3
"""
Generate samples.inc — 4-bit vocal digi samples for $D418 playback.

Cuts the key vocal phrases out of the AI-separated vocal stem of music.mp3
(the project's own track), downsamples them to the CIA-timer rate, packs two
4-bit samples per byte and emits:

  * the sample data (placed at $7000)
  * per-sample start/end address tables
  * a digi cue list (bar, frame-in-bar, sample id) that matches the demo's
    93-frames-per-bar timeline, for verse 1, verse 2 (+32 bars) and one
    final "fantastisk" in the finale.

Usage:  python3 gen_samples.py <vocals.wav>
The trimmed phrases are also written to vocals/ as reference WAVs (they feed
the Amiga port, which plays them as proper Paula samples).

If <vocals.wav> is missing the script exits 0 without touching samples.inc,
so the committed include keeps working.
"""
import os
import sys
import wave

import numpy as np

OUT = os.path.dirname(os.path.abspath(__file__))

PAL_CLK = 985248
TIMER = 189                       # CIA period -> 5213 Hz sample rate
RATE = PAL_CLK / TIMER
FIRST = 0.408                     # first downbeat in music.mp3
BAR_S = 93 / 50.0                 # our demo bar length in seconds
ORG = 0x7000

# name, rough window (s), trigger also in finale?
PHRASES = [
    ('kattene', 7.45, 8.95, False),
    ('oohh', 12.80, 14.40, False),
    ('hestene', 15.30, 16.80, False),
    ('fantastisk', 30.90, 33.95, True),
]


def load_wav(path):
    w = wave.open(path)
    sr = w.getframerate()
    n = w.getnframes()
    x = np.frombuffer(w.readframes(n), dtype=np.int16).astype(np.float64)
    if w.getnchannels() == 2:
        x = x.reshape(-1, 2).mean(axis=1)
    return x / 32768.0, sr


def refine(x, sr, t0, t1):
    """Trim the window to where the vocal actually has energy."""
    seg = x[int(t0 * sr):int(t1 * sr)]
    win = int(0.02 * sr)
    e = np.convolve(seg ** 2, np.ones(win) / win, mode='same')
    thr = e.max() * 0.004
    idx = np.where(e > thr)[0]
    if len(idx) == 0:
        return t0, t1
    return t0 + idx[0] / sr, t0 + min(len(seg) - 1, idx[-1] + win) / sr


def resample(seg, sr):
    n_out = int(len(seg) * RATE / sr)
    # simple windowed mean decimation (the target is 4-bit lo-fi anyway)
    pos = np.linspace(0, len(seg), n_out + 1).astype(int)
    return np.array([seg[a:b].mean() if b > a else seg[min(a, len(seg) - 1)]
                     for a, b in zip(pos[:-1], pos[1:])])


def to_nibbles(seg):
    peak = np.abs(seg).max() + 1e-9
    seg = seg / peak
    seg = np.sign(seg) * np.abs(seg) ** 0.65          # mild companding
    fade = int(0.01 * RATE)
    seg[:fade] *= np.linspace(0, 1, fade)
    seg[-fade:] *= np.linspace(1, 0, fade)
    q = np.clip(np.round((seg + 1) / 2 * 15), 0, 15).astype(int)
    if len(q) & 1:
        q = np.append(q, 8)
    return q


def main():
    if len(sys.argv) < 2 or not os.path.exists(sys.argv[1]):
        print('gen_samples.py: no vocal stem given/found - keeping the '
              'committed samples.inc')
        return
    x, sr = load_wav(sys.argv[1])
    os.makedirs(os.path.join(OUT, 'vocals'), exist_ok=True)

    blobs = []
    cues = []                     # (bar, frame, sample-id)
    for i, (name, t0, t1, in_finale) in enumerate(PHRASES):
        a, b = refine(x, sr, t0, t1)
        seg = x[int(a * sr):int(b * sr)]
        # reference wav for the Amiga port
        ref = os.path.join(OUT, 'vocals', name + '.wav')
        w = wave.open(ref, 'w')
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(sr)
        w.writeframes((np.clip(seg, -1, 1) * 32767).astype('<i2').tobytes())
        w.close()

        q = to_nibbles(resample(seg, sr))
        packed = bytes((q[j] << 4) | q[j + 1] for j in range(0, len(q), 2))
        blobs.append(packed)

        fa = max(0, round((a - FIRST) * 50))
        bar, fr = divmod(fa, 93)
        cues.append((bar, fr, i))
        cues.append((bar + 32, fr, i))            # verse 2 repeat
        if in_finale:
            cues.append((58, 0, i))               # one last hook shout
        print(f'{name:11s} {a:6.2f}-{b:5.2f}s  {len(packed):5d} bytes  '
              f'cue bar {bar} frame {fr}')

    cues.sort()
    total = sum(len(b) for b in blobs)
    end = ORG + total
    assert end < 0xD000, f'samples run into I/O space: end=${end:04x}'

    with open(os.path.join(OUT, 'samples.inc'), 'w') as f:
        f.write('; --- Auto-generated by gen_samples.py — vocal digis ---\n')
        f.write('; 4-bit packed samples for the $d418 volume-DAC trick.\n')
        f.write(f'; rate {RATE:.0f} Hz (CIA timer {TIMER}), '
                f'{total} bytes total\n\n')
        f.write(f'DIGI_TIMER = {TIMER}\n')
        f.write(f'NUM_DIGI_CUES = {len(cues)}\n\n')
        addr = ORG
        starts = []
        for (name, *_), blob in zip(PHRASES, blobs):
            starts.append(addr)
            addr += len(blob)
        f.write('smp_lo:  !byte ' +
                ','.join(f'<${a:04x}' for a in starts) + '\n')
        f.write('smp_hi:  !byte ' +
                ','.join(f'>${a:04x}' for a in starts) + '\n')
        ends = starts[1:] + [addr]
        f.write('smpe_lo: !byte ' +
                ','.join(f'<${a:04x}' for a in ends) + '\n')
        f.write('smpe_hi: !byte ' +
                ','.join(f'>${a:04x}' for a in ends) + '\n')
        f.write('dcue_bar: !byte ' +
                ','.join(str(c[0]) for c in cues) + ',$ff\n')
        f.write('dcue_fr:  !byte ' +
                ','.join(str(c[1]) for c in cues) + ',$ff\n')
        f.write('dcue_smp: !byte ' +
                ','.join(str(c[2]) for c in cues) + ',$ff\n\n')
        f.write(f'        * = ${ORG:04x}\n')
        f.write('digi_data:\n')
        for blob in blobs:
            for j in range(0, len(blob), 16):
                f.write('        !byte ' +
                        ','.join(f'${b:02x}' for b in blob[j:j + 16]) + '\n')
    print(f'samples.inc written: {total} bytes at ${ORG:04x}-${end:04x}, '
          f'{len(cues)} cues')


if __name__ == '__main__':
    main()
