; ===================================================================
;  MOTORSAG ARKITEKT  -  SID music driver  (PAL, 50 Hz)
; -------------------------------------------------------------------
;  A small 3-voice tracker-style driver, called once per frame.
;  The song data (music_data.inc) is generated by gen_music.py from a
;  transcription of the original track: E minor, 129.03 BPM (93 frames
;  per bar), 64 bars, through-composed with the hook landing on E major.
;
;  Per-voice SID character:
;    * arpeggios       (the classic chord shimmer)
;    * pulse-width mod (moving, ping-ponged PWM sweep)
;    * vibrato         (delayed, on the leads)
;    * gate retrigger inside the frame for punchy attacks
;
;  Event stream format (one long stream per voice):
;    $01..$60 , dur   : play note (1..96 = C-0..B-7) for dur frames
;    $00      , dur   : rest (gate off) for dur frames
;    $FD      , dur   : tie/hold current note for dur frames (no retrig)
;    $FE      , inst  : select instrument
;    $FF              : end of stream -> loop this voice from its start
; ===================================================================

SID = $d400

; ---- zero page scratch used by the player ----
mptr = $f8          ; stream read pointer (16-bit)
enote = $fc         ; effective note (byte)
frq   = $fd         ; working frequency (16-bit: $fd/$fe)

; -------------------------------------------------------------------
;  Initialise the player: silence SID, reset all voice state.
; -------------------------------------------------------------------
!zone
music_init:
        ; clear all 25 SID registers
        lda #0
        ldx #24
-       sta SID,x
        dex
        bpl -
        sta beat_flag

        ; set volume to max (no filter routing)
        lda #$0f
        sta SID+24

        ; per-voice: rewind stream, force a fetch on the first tick
        ldx #2
.vi:
        lda song_start_lo,x
        sta pat_lo,x
        lda song_start_hi,x
        sta pat_hi,x
        lda #0
        sta v_wait,x            ; 0 -> fetch on first tick
        sta v_note,x
        sta v_arpidx,x
        sta v_vibph,x
        dex
        bpl .vi
        rts

; -------------------------------------------------------------------
;  Main entry - call once per frame (50 Hz) from the raster IRQ.
; -------------------------------------------------------------------
!zone
music_play:
        ldx #0
.loop:
        stx vx
        lda v_wait,x
        bne .nofetch
        jsr fetch_event         ; X = voice, sets note/rest/tie + wait
        ldx vx
.nofetch:
        dec v_wait,x
        jsr voice_effects       ; applies arp/vib/pwm, writes freq/pw
        ldx vx
        inx
        cpx #3
        bne .loop
        rts

; -------------------------------------------------------------------
;  fetch_event : advance voice X to its next note/rest/tie.
;  Loops internally over zero-length commands (inst set, end-of-song).
; -------------------------------------------------------------------
!zone
fetch_event:
        lda pat_lo,x
        sta mptr
        lda pat_hi,x
        sta mptr+1
.next:
        ldy #0
        lda (mptr),y
        cmp #$ff
        bne .not_end
        ; end of stream -> loop this voice from its start
        ldx vx
        lda song_start_lo,x
        sta mptr
        lda song_start_hi,x
        sta mptr+1
        jmp .next
.not_end:
        cmp #$fe
        bne .not_inst
        ; select instrument (byte after)
        ldy #1
        lda (mptr),y
        ldx vx
        jsr load_instrument     ; A = inst id, X = voice
        jsr adv2
        jmp .next
.not_inst:
        cmp #$fd
        bne .not_tie
        ; tie: keep sounding, just set wait (no retrigger)
        ldy #1
        lda (mptr),y
        ldx vx
        sta v_wait,x
        jsr adv2
        jmp .store
.not_tie:
        cmp #$00
        bne .is_note
        ; rest: gate off, set wait
        ldy #1
        lda (mptr),y
        ldx vx
        sta v_wait,x
        ldy sidoff,x
        lda v_wave,x
        and #$fe                ; clear gate bit -> release
        sta SID+4,y
        jsr adv2
        jmp .store
.is_note:
        ; note 1..96 in A
        ldx vx
        sta v_note,x
        ldy #1
        lda (mptr),y
        sta v_wait,x
        jsr trigger_note        ; X = voice
        jsr adv2
        ; fall through to store
.store:
        ldx vx
        lda mptr
        sta pat_lo,x
        lda mptr+1
        sta pat_hi,x
        rts

; advance mptr by 2
!zone
adv2:
        lda mptr
        clc
        adc #2
        sta mptr
        bcc +
        inc mptr+1
+       rts

; -------------------------------------------------------------------
;  load_instrument : A = inst id, X = voice.  Copies inst params
;  into the voice's live state.
; -------------------------------------------------------------------
!zone
load_instrument:
        sta v_inst,x
        tay
        lda in_wave,y
        sta v_wave,x
        lda in_ad,y
        sta v_ad,x
        lda in_sr,y
        sta v_sr,x
        lda in_pwlo,y
        sta v_pwlo,x
        lda in_pwhi,y
        sta v_pwhi,x
        lda in_pwspd,y
        sta v_pwspd,x
        lda in_arp,y
        sta v_arpbase,x
        lda in_vib,y
        sta v_vibset,x
        rts

; -------------------------------------------------------------------
;  trigger_note : X = voice.  Program ADSR/PW, retrigger gate,
;  reset arp + vibrato phase.  Flags a beat on the snare.
; -------------------------------------------------------------------
!zone
trigger_note:
        ldy sidoff,x
        lda v_ad,x
        sta SID+5,y
        lda v_sr,x
        sta SID+6,y
        lda v_pwlo,x
        sta SID+2,y
        lda v_pwhi,x
        sta SID+3,y
        ; hard-ish restart: gate off then on within the frame
        lda v_wave,x
        and #$fe
        sta SID+4,y
        lda v_wave,x
        ora #$01
        sta SID+4,y
        lda #0
        sta v_arpidx,x
        sta v_vibph,x
        lda #VIB_DELAY
        sta v_vibdelay,x
        ; backbeat flash: the drum/lead voice playing the SNARE
        cpx #0
        bne +
        lda v_inst,x
        cmp #SNARE
        bne +
        lda #1
        sta beat_flag
+       rts

; -------------------------------------------------------------------
;  voice_effects : X = voice.  Per-frame arp + vibrato + PWM.
;  Writes the final frequency and (if sweeping) pulse width.
; -------------------------------------------------------------------
!zone
voice_effects:
        ldx vx
        lda v_note,x
        bne +
        rts                     ; note 0 -> nothing sounding
+       sta enote

        ; ---- arpeggio ----
        lda v_arpbase,x
        cmp #$ff
        beq .noarp
        clc
        adc v_arpidx,x
        tay
        lda arp_data,y
        cmp #$81
        beq .arphold            ; hold: offset 0, freeze index
        cmp #$80
        bne .arpadd
        ; loop marker -> reset index, re-read first entry
        lda #0
        sta v_arpidx,x
        ldy v_arpbase,x
        lda arp_data,y
.arpadd:
        clc
        adc enote
        sta enote
        inc v_arpidx,x
        jmp .noarp
.arphold:
        ; keep enote as-is, do not advance index
.noarp:
        ; ---- base frequency from table ----
        ldy enote
        dey
        lda freqtbl_lo,y
        sta frq
        lda freqtbl_hi,y
        sta frq+1

        ; ---- vibrato ----
        lda v_vibset,x
        beq .novib
        lda v_vibdelay,x
        beq .vibgo
        dec v_vibdelay,x
        jmp .novib
.vibgo:
        lda v_vibset,x
        and #$0f
        clc
        adc v_vibph,x
        sta v_vibph,x
        and #$1f                ; 32-entry table
        tay
        lda vibsine,y
        bpl .vpos
        ; negative delta (signed add)
        clc
        adc frq
        sta frq
        lda frq+1
        adc #$ff
        sta frq+1
        jmp .novib
.vpos:
        clc
        adc frq
        sta frq
        bcc .novib
        inc frq+1
.novib:
        ; ---- write frequency ----
        ldy sidoff,x
        lda frq
        sta SID+0,y
        lda frq+1
        sta SID+1,y

        ; ---- pulse-width sweep (ping-pong) ----
        lda v_pwspd,x
        beq .done
        bmi .pwneg
        ; positive
        clc
        adc v_pwlo,x
        sta v_pwlo,x
        bcc .pwbound
        inc v_pwhi,x
        jmp .pwbound
.pwneg:
        clc
        adc v_pwlo,x
        sta v_pwlo,x
        bcs .pwbound
        dec v_pwhi,x
.pwbound:
        lda v_pwhi,x
        and #$0f
        cmp #$0e
        bcs .pwflip
        cmp #$02
        bcc .pwflip
        jmp .pwwrite
.pwflip:
        lda #0
        sec
        sbc v_pwspd,x
        sta v_pwspd,x
.pwwrite:
        ldy sidoff,x
        lda v_pwlo,x
        sta SID+2,y
        lda v_pwhi,x
        and #$0f
        sta SID+3,y
.done:
        rts

; ===================================================================
;  DATA
; ===================================================================

sidoff  !byte 0, 7, 14

; ---- per-voice live state (3 bytes each) ----
pat_lo      !byte 0,0,0
pat_hi      !byte 0,0,0
v_wait      !byte 0,0,0
v_note      !byte 0,0,0
v_inst      !byte 0,0,0
v_wave      !byte 0,0,0
v_ad        !byte 0,0,0
v_sr        !byte 0,0,0
v_pwlo      !byte 0,0,0
v_pwhi      !byte 0,0,0
v_pwspd     !byte 0,0,0
v_arpbase   !byte 0,0,0
v_arpidx    !byte 0,0,0
v_vibset    !byte 0,0,0
v_vibph     !byte 0,0,0
v_vibdelay  !byte 0,0,0
vx          !byte 0
beat_flag   !byte 0

VIB_DELAY = 10

; ===================================================================
;  INSTRUMENTS   (ids must match gen_music.py)
;    0 LEAD   1 ARPM   2 ARPJ   3 BASS   4 KICK
;    5 SNARE  6 HAT    7 LEAD2  8 PAD    9 ARP7
; ===================================================================
;              LEAD  ARPM  ARPJ  BASS  KICK  SNARE HAT   LEAD2 PAD   ARP7
in_wave   !byte $40 , $20 , $20 , $40 , $10 , $80 , $80 , $40 , $10 , $20
in_ad     !byte $09 , $0a , $0a , $08 , $08 , $08 , $04 , $09 , $8a , $0a
in_sr     !byte $a9 , $89 , $89 , $68 , $00 , $00 , $00 , $b8 , $c8 , $89
in_pwlo   !byte $00 , $00 , $00 , $00 , $00 , $00 , $00 , $00 , $00 , $00
in_pwhi   !byte $08 , $06 , $06 , $08 , $08 , $08 , $08 , $04 , $08 , $06
in_pwspd  !byte $30 , $18 , $18 , $00 , $00 , $00 , $00 , $28 , $00 , $18
in_arp    !byte $ff , ARP_MIN_OFS , ARP_MAJ_OFS , ARP_BASS_OFS , ARP_KICK_OFS , $ff , $ff , $ff , $ff , ARP_DOM7_OFS
in_vib    !byte $03 , $00 , $00 , $00 , $00 , $00 , $00 , $04 , $02 , $00

; instrument id constants (SNARE used by trigger_note's beat flag)
LEAD=0 : ARPM=1 : ARPJ=2 : BASS=3 : KICK=4
SNARE=5 : HAT=6 : LEAD2=7 : PAD=8 : ARP7=9

; ---- arpeggio tables : signed semitone offsets ----
;   $80 = loop to start of this arp,  $81 = hold last (freeze)
ARP_MIN_OFS  = 0
ARP_MAJ_OFS  = 5
ARP_DOM7_OFS = 10
ARP_BASS_OFS = 15
ARP_KICK_OFS = 19
arp_data
        !byte 0, 3, 7, 12, $80          ;  0 minor
        !byte 0, 4, 7, 12, $80          ;  5 major
        !byte 0, 4, 7, 10, $80          ; 10 dominant 7th
        !byte 5, 2, 0, $81              ; 15 bass pitch-thump then hold
        !byte 30,20,12,6,0,$81          ; 19 kick pitch drop

; ---- per-voice stream start addresses ----
; (the song data itself -- music_data.inc -- is included by the top-level
;  file so the demo can place it away from the code segment)
song_start_lo !byte <song_v1, <song_v2, <song_v3
song_start_hi !byte >song_v1, >song_v2, >song_v3
